import Image from "next/image";
import Link from "next/link";

import { LiveMarketPreview } from "@/components/market/LiveMarketPreview";
import { Arrow } from "@/components/ui/Arrow";
import { Button } from "@/components/ui/Button";
import { SectionLabel } from "@/components/ui/SectionLabel";
import { brandAssets } from "@/lib/brand";

export default function HomePage() {
  return <>
    <section className="band band-sky hero-band"><div className="band-inner hero-inner"><div><p className="eyebrow">The stock market, in orbit</p><h1 className="hero-title">Trade <span className="blue">ideas</span>, not noise.</h1><p className="hero-copy">Percorium is the quiet place to discover and trade official Sunrise-listed stocks and ETFs on Solana. Your wallet signs every move.</p><div className="hero-actions"><Button href="/trade">Start a trade <Arrow /></Button><Button href="/assets" variant="secondary">Browse assets</Button></div></div><div className="hero-art"><Image className="hero-bot-image" src={brandAssets.logo.bot} alt="Percorium bot" width={577} height={433} priority /></div></div></section>
    <section className="band band-white"><div className="band-inner"><div className="section-heading"><div><SectionLabel>Make your move</SectionLabel><h2>Simple rails.<br />Real ownership.</h2></div><p>From a first ticker to a shareable basket, every surface is built around one clear action and one honest status.</p></div><div className="card-grid"><article className="sticker-panel panel-blue"><Image className="panel-icon" src={brandAssets.categories.stock} alt="" width={56} height={56} /><h3>Official by default</h3><p>Search the Sunrise list. No guessed mints, no mystery assets.</p></article><article className="sticker-panel panel-yellow"><Image className="panel-icon" src={brandAssets.states.success} alt="" width={56} height={56} /><h3>Your wallet signs</h3><p>Review the quote, approve the transaction, keep control.</p></article><article className="sticker-panel panel-lavender"><Image className="panel-icon" src={brandAssets.categories.etf} alt="" width={56} height={56} /><h3>Ideas travel well</h3><p>Build a basket, gift an asset, or share a prefilled buy.</p></article></div></div></section>
    <section className="band band-gray"><div className="band-inner market-strip"><div className="market-copy"><div><SectionLabel>Live market</SectionLabel><h2>Find your next orbit.</h2><p>Market quotes refresh from the API. Eligibility still comes only from the official asset allowlist.</p></div><Link className="button button-secondary" href="/assets">Explore all assets <Arrow /></Link></div><LiveMarketPreview /></div></section>
    <section className="band band-white app-band"><div className="band-inner"><div className="app-card"><div><SectionLabel>Designed for the decisive</SectionLabel><h2>One ticket.<br />No theatre.</h2><p>Trade SOL or USDC into official stock and ETF mints. Review a 50 bps fee, then sign. Limit and DCA rails are available from the same ticket.</p><Button href="/trade" variant="secondary">Open the trade ticket <Arrow /></Button></div><div className="app-art"><Image src={brandAssets.logo.mark} alt="" width={160} height={160} /></div></div></div></section>
  </>;
}