import Image from "next/image";
import Link from "next/link";

import { Badge } from "@/components/ui/Badge";
import { SectionLabel } from "@/components/ui/SectionLabel";
import { StatusPill } from "@/components/ui/StatusPill";
import { brandAssets } from "@/lib/brand";

export default function MorePage() {
  return <><section className="band band-lavender"><div className="page-shell"><div className="page-hero"><div><SectionLabel>Protocols and controls</SectionLabel><h1>More ways<br />to move.</h1></div><div><StatusPill status="pending">Available by market</StatusPill><p>Put eligible assets to work, keep privacy close, and tune the parts of Percorium that follow you.</p></div></div></div></section><section className="band band-white"><div className="page-shell"><div className="section-heading"><div><SectionLabel>Earn, where available</SectionLabel><h2>Put idle assets<br />to work.</h2></div><Image src={brandAssets.categories.sector} alt="" width={72} height={72} /></div><div className="card-grid"><article className="sticker-panel panel-lavender"><div><Badge tone="violet">LIQUIDITY</Badge><h3>LP</h3></div><p>Sign in-app to add liquidity to the real pool when a market exists.</p></article><article className="sticker-panel panel-white"><div><Badge tone="neutral">MONEY MARKETS</Badge><h3>Lend / borrow</h3></div><p>Show only mint markets discoverable on Kamino or Jupiter Lend.</p></article><article className="sticker-panel panel-gray"><div><Badge tone="blue">PRIVACY</Badge><h3>MagicBlock</h3></div><p>Off by default. Turn on the privacy mode from Settings when you need it.</p></article></div></div></section><section className="band band-sky"><div className="page-shell"><div className="section-heading"><div><SectionLabel>Keep your orbit in order</SectionLabel><h2>Controls that<br />stay close.</h2></div><p>Settings and gifting live here when they are not part of the trade itself.</p></div><div className="ticket-layout"><Link className="product-card product-card-white" href="/settings"><SectionLabel>Preferences</SectionLabel><h3>Open Settings</h3><p>Manage Base visibility, identity, SNS linking, privacy, and your MCP URL.</p><span className="arrow">→</span></Link><Link className="product-card product-card-white" href="/gifts"><SectionLabel>Send value</SectionLabel><h3>Give a gift</h3><p>Create a Jupiter-style claim link for an official Sunrise asset.</p><span className="arrow">→</span></Link></div></div></section></>;
}