import Image from "next/image";

import { brandAssets } from "@/lib/brand";
import { Button } from "@/components/ui/Button";
import { StatusPill } from "@/components/ui/StatusPill";
import { SectionLabel } from "@/components/ui/SectionLabel";

export default function TradePage() {
  return <section className="band band-sky"><div className="page-shell"><div className="page-hero"><div><SectionLabel>Sunrise · Solana</SectionLabel><h1>Trade<br />with intent.</h1></div><div><StatusPill status="pending">Awaiting wallet</StatusPill><p>Your wallet signs. Percorium prepares.</p></div></div><div className="ticket-layout"><section className="product-card product-card-white"><div className="trade-tabs"><button className="trade-tab active">Swap</button><button className="trade-tab">Limit</button><button className="trade-tab">DCA</button></div><div className="field-grid"><label className="field">You pay<select defaultValue="USDC"><option>USDC</option><option>SOL</option></select></label><label className="field">You receive<select defaultValue="AAPL · Apple"><option>AAPL · Apple</option><option>NVDA · NVIDIA</option><option>QQQ · Nasdaq 100</option></select></label></div><label className="field">Amount<input placeholder="0.00" inputMode="decimal" /></label><div className="fee-line"><span>Route</span><strong>Sunrise → Solana</strong></div><div className="fee-line"><span>Platform fee</span><strong>50 bps</strong></div><Button>Review quote</Button></section><aside className="product-card product-card-gray"><SectionLabel>Before you sign</SectionLabel><Image src={brandAssets.states.pending} alt="Pending transaction" width={64} height={64} /><h3>Review every move.</h3><p>Quotes, slippage, and fees stay visible before the wallet prompt. Nothing moves without your approval.</p><StatusPill status="warning">No wallet connected</StatusPill></aside></div><div className="card-grid page-section"><article className="sticker-panel panel-blue"><SectionLabel>Market</SectionLabel><h3>Stock → stock</h3><p>Switch between supported official mints in one ticket.</p></article><article className="sticker-panel panel-lavender"><SectionLabel>Scheduled</SectionLabel><h3>DCA, on your terms</h3><p>Jupiter Trigger V2 integration boundary is ready.</p></article><article className="sticker-panel panel-yellow"><SectionLabel>Private</SectionLabel><h3>Quiet fills</h3><p>Private trades never become social callouts.</p></article></div></div></section>;
}